// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/7/2026, 8:46:14 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/kode/Desktop/KODETECH/Cop/Cop-dues-tracker/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kode/Desktop/KODETECH/Cop/Cop-dues-tracker/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kode/Desktop/KODETECH/Cop/Cop-dues-tracker/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kode/Desktop/KODETECH/Cop/Cop-dues-tracker/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kode/Desktop/KODETECH/Cop/Cop-dues-tracker/app/plugins/**/*.{js,ts,mjs}","/Users/kode/Desktop/KODETECH/Cop/Cop-dues-tracker/app/composables/**/*.{js,ts,mjs}","/Users/kode/Desktop/KODETECH/Cop/Cop-dues-tracker/app/utils/**/*.{js,ts,mjs}","/Users/kode/Desktop/KODETECH/Cop/Cop-dues-tracker/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kode/Desktop/KODETECH/Cop/Cop-dues-tracker/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kode/Desktop/KODETECH/Cop/Cop-dues-tracker/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kode/Desktop/KODETECH/Cop/Cop-dues-tracker/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;